# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-18 01:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171117_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 1, 23, 34, 761554, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
